version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "docker@123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "apisolid"
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data